apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-phpbb
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: phpmyadmin-deployment
 minReplicas: 5
 maxReplicas: 10
 targetCPUUtilizationPercentage: 70