apiVersion: v1
kind: Service
metadata:
  name: fastapisvc
spec:
  selector:
    app: fastapi
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: ubuntu:20.04
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            requests:
              cpu: "250m"
          command: ["/bin/sh"]
          args:
              - -c
              - >-
                  apt-get update &&
                  apt-get install software-properties-common -y &&
                  add-apt-repository ppa:deadsnakes/ppa -y &&
                  apt-get update && 
                  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata &&
                  apt-get install python3.8 python3-pip -y &&
                  apt install git -y &&
                  update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 &&
                  python3 --version &&
                  command -v pip3 &&
                  pip3 install fastapi uvicorn --no-input &&
                  git clone https://github.com/DataScientest/kubernetes-devops-project &&
                  cd kubernetes-devops-project &&
                  cp requirements.txt /usr/src/requirements.txt &&
                  pip3 install --no-cache-dir -r /usr/src/requirements.txt &&
                  sed -i 's/localhost/app1.mpcloud.cloudns.ph/' ./config/dp.py &&
                  uvicorn app:app --host 0.0.0.0 --port 8080
