apiVersion: v1
kind: PersistentVolume
metadata:
  name: datascientest-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/volume"
  storageClassName: default
