apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace : {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 10Gi