apiVersion: {{ .Values.apiversion }}
kind: Service
metadata:
  name: {{ .Values.mysql.servicename }}
  namespace : {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.mysql.appname }}
  ports:
    - protocol: "TCP"
      port: 3306
      targetPort: 3306
  type: LoadBalancer