apiVersion: {{ .Values.apiversion }}
kind: Service
metadata:
  name: {{ .Values.phpmyadmin.servicename }}
  namespace : {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.phpmyadmin.appname }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80