apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa
 namespace : {{ .Values.namespace }}
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ .Values.fastapi.appname }}
 minReplicas: {{ .Values.autoscaler.min }}
 maxReplicas: {{ .Values.autoscaler.max }}
 targetCPUUtilizationPercentage: {{ .Values.fastapi.usepercentage }}