# Default values for HELM.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace : helm
apiversion : v1
pv:
  name: datascientest-pv-h
  storageClassName: default

pvc:
  name: pvc

secret:
  name: mysql-secret

mysql:
  appname: mysql
  servicename: mysqlsvc

phpmyadmin:
  appname: phpmyadmin
  servicename : phpmyadmin-service

fastapi:
  appname: fastapi
  servicename : fastapisvc

autoscaler:
  min: 5
  max: 10
  usepercentage: 70
